# 1. ${base}/src/main/resources/*.properties
# 2. ${base}/src/main/resources/config/*.properties
# 3. ${base}/*.properties
# 4. ${base}/config/*.properties

spring.config.location=optional:file:./dev/config/*/
